const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

/**
 * Generate a PDF certificate for a volunteer
 * @param {Object} data - Certificate data
 * @param {string} data.volunteerName - Volunteer name
 * @param {string} data.eventName - Event name
 * @param {string} data.eventDate - Event date
 * @param {number} data.hoursCompleted - Hours completed
 * @param {string} data.certificateId - Certificate ID
 * @param {string} data.issuedBy - Issuing organization
 * @returns {Buffer} PDF buffer
 */
const generateCertificate = async (data) => {
    const uploadsDir = path.join(__dirname, '..', 'uploads', 'certificates');
    if (!fs.existsSync(uploadsDir)) {
        fs.mkdirSync(uploadsDir, { recursive: true });
    }

    const filePath = path.join(uploadsDir, `${data.certificateId}.pdf`);

    const doc = new PDFDocument({
        size: 'A4',
        layout: 'landscape',
        margins: { top: 50, bottom: 50, left: 50, right: 50 }
    });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Background border
    doc.rect(20, 20, doc.page.width - 40, doc.page.height - 40)
        .lineWidth(3)
        .strokeColor('#2E86AB')
        .stroke();

    // Inner decorative border
    doc.rect(30, 30, doc.page.width - 60, doc.page.height - 60)
        .lineWidth(1)
        .strokeColor('#A23B72')
        .stroke();

    // Header - Organization Name
    doc.fontSize(28)
        .font('Helvetica-Bold')
        .fillColor('#2E86AB')
        .text('NAYEPANKH FOUNDATION', 0, 60, { align: 'center' });

    // Subtitle
    doc.fontSize(14)
        .font('Helvetica')
        .fillColor('#A23B72')
        .text('ServeTogether Volunteer Program', 0, 95, { align: 'center' });

    // Certificate Title
    doc.fontSize(36)
        .font('Helvetica-Bold')
        .fillColor('#F18F01')
        .text('CERTIFICATE OF APPRECIATION', 0, 130, { align: 'center' });

    // Decorative line
    doc.moveTo(100, 175)
        .lineTo(doc.page.width - 100, 175)
        .lineWidth(2)
        .strokeColor('#2E86AB')
        .stroke();

    // "This is proudly presented to"
    doc.fontSize(16)
        .font('Helvetica')
        .fillColor('#333333')
        .text('This is proudly presented to', 0, 195, { align: 'center' });

    // Volunteer Name
    doc.fontSize(30)
        .font('Helvetica-Bold')
        .fillColor('#2E86AB')
        .text(data.volunteerName, 0, 220, { align: 'center' });

    // Description
    doc.fontSize(14)
        .font('Helvetica')
        .fillColor('#333333')
        .text('For their outstanding contribution and dedicated service as a volunteer', 0, 260, { align: 'center' });

    doc.fontSize(14)
        .font('Helvetica-Bold')
        .fillColor('#A23B72')
        .text(`at "${data.eventName}"`, 0, 280, { align: 'center' });

    // Event details
    const eventDateStr = new Date(data.eventDate).toLocaleDateString('en-IN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });

    doc.fontSize(12)
        .font('Helvetica')
        .fillColor('#333333')
        .text(`Date: ${eventDateStr}  |  Hours Volunteered: ${data.hoursCompleted}`, 0, 310, { align: 'center' });

    // Certificate ID
    doc.fontSize(10)
        .font('Helvetica')
        .fillColor('#666666')
        .text(`Certificate ID: ${data.certificateId}`, 0, 340, { align: 'center' });

    // Signature section
    doc.fontSize(12)
        .font('Helvetica')
        .fillColor('#333333')
        .text('Authorized by', 80, 380);

    doc.moveTo(80, 410)
        .lineTo(250, 410)
        .lineWidth(1)
        .strokeColor('#333333')
        .stroke();

    doc.fontSize(11)
        .font('Helvetica-Bold')
        .text(data.issuedBy || 'Nayepankh Foundation', 80, 415);

    // Right side signature
    doc.fontSize(12)
        .font('Helvetica')
        .fillColor('#333333')
        .text('Program Coordinator', doc.page.width - 280, 380);

    doc.moveTo(doc.page.width - 280, 410)
        .lineTo(doc.page.width - 100, 410)
        .lineWidth(1)
        .strokeColor('#333333')
        .stroke();

    doc.fontSize(11)
        .font('Helvetica-Bold')
        .text('ServeTogether', doc.page.width - 280, 415);

    // Footer
    doc.fontSize(9)
        .font('Helvetica')
        .fillColor('#999999')
        .text('This certificate is auto-generated by ServeTogether - Nayepankh Foundation Volunteer Management System', 0, doc.page.height - 60, { align: 'center' });

    doc.end();

    return new Promise((resolve, reject) => {
        stream.on('finish', () => {
            resolve(filePath);
        });
        stream.on('error', (err) => {
            reject(err);
        });
    });
};

module.exports = { generateCertificate };
